language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean spring-boot:run -DskipTests -Dimaps.mail.username=${user} -Dimaps.mail.password=${password} -Dimaps.mail.host=${host} -Dspring.profiles.active=junit -Dspring.main.sources=com.deere.isg.tx.excel.config.ExcelConfig